apiVersion: apps/v1
kind: Deployment
metadata:
  name: seller-service-ui-deployment
  labels:
    app: seller-service-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seller-service-ui
  template:
    metadata:
      labels:
        app: seller-service-ui
    spec:
      containers:
        - name: seller-service-ui
          image: systeamorg/seller-service-ui
          env:
            - name: PORT
              value: "85"
          imagePullPolicy: Never
          ports:
            - containerPort: 85

---
apiVersion: v1
kind: Service
metadata:
  name: seller-service-ui
  labels:
    app: seller-service-ui
spec:
  ports:
    - port: 85
      targetPort: 85
      protocol: TCP
      name: tcp
      nodePort: 30085
  type: NodePort
  selector:
    app: seller-service-ui